datamart:
  target: dev
  outputs:
    dev:
      type: postgres
      host: "{{ env_var('DBT_HOST') }}"
      user: "{{ env_var('DBT_USER') }}"
      password: "{{ env_var('DBT_PASS') }}"
      port: "{{ env_var('DBT_PORT', '5432') | as_number }}"
      dbname: "{{ env_var('DBT_DBNAME', 'db_geisler_prueba') }}"
      schema: gold # dbt escribirá todo el modelo estrella directamente en la capa Gold
      threads: 4
